/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-dim': '#eed198',
        'inverse-primary': '#7e29df',
        secondary: '#e5e2e1',
        'on-primary-fixed-variant': '#3f007c',
        'secondary-container': '#474646',
        'error-dim': '#d73357',
        'primary-container': '#ba88ff',
        'error-container': '#a70138',
        'outline-variant': '#6b6a6f',
        'tertiary-fixed': '#fddfa5',
        'surface-variant': '#2e2d31',
        'surface-tint': '#c59aff',
        'on-primary': '#420082',
        'on-secondary-container': '#d2d0cf',
        'on-primary-fixed': '#000000',
        'tertiary-container': '#fddfa5',
        'on-tertiary-fixed-variant': '#6e592b',
        'secondary-dim': '#d7d4d3',
        'primary-dim': '#9547f7',
        'on-surface': '#fffbfe',
        'surface-bright': '#36363a',
        'tertiary-fixed-dim': '#eed198',
        'secondary-fixed': '#e5e2e1',
        'on-tertiary': '#6c572a',
        'inverse-on-surface': '#565457',
        'on-primary-container': '#330066',
        'secondary-fixed-dim': '#d7d4d3',
        outline: '#767578',
        'on-secondary-fixed-variant': '#5c5b5b',
        'surface-dim': '#0e0e10',
        'on-surface-variant': '#adaaad',
        'on-error-container': '#ffb2b9',
        'on-error': '#490013',
        'on-background': '#fffbfe',
        'on-secondary': '#525151',
        background: '#0e0e10',
        'inverse-surface': '#fcf8fb',
        surface: '#0e0e10',
        'on-secondary-fixed': '#403f3f',
        'surface-container-high': '#2a2a2e',
        'surface-container': '#222226',
        'on-tertiary-fixed': '#4f3d11',
        primary: '#c59aff',
        'primary-fixed-dim': '#b075ff',
        tertiary: '#ffefd5',
        error: '#ff6e84',
        'surface-container-highest': '#313035',
        'surface-container-lowest': '#000000',
        'primary-fixed': '#ba88ff',
        'on-tertiary-container': '#634f22',
        'surface-container-low': '#1b1b1e',
        'skill-rose': '#e879a0',
      },
      fontSize: {
        xs:   ['calc(0.75rem * var(--_fs-mult, 1))',   { lineHeight: 'calc(1rem * var(--_fs-mult, 1))' }],
        sm:   ['calc(0.875rem * var(--_fs-mult, 1))',  { lineHeight: 'calc(1.25rem * var(--_fs-mult, 1))' }],
        base: ['calc(1rem * var(--_fs-mult, 1))',      { lineHeight: 'calc(1.5rem * var(--_fs-mult, 1))' }],
        lg:   ['calc(1.125rem * var(--_fs-mult, 1))',  { lineHeight: 'calc(1.75rem * var(--_fs-mult, 1))' }],
        xl:   ['calc(1.25rem * var(--_fs-mult, 1))',   { lineHeight: 'calc(1.75rem * var(--_fs-mult, 1))' }],
        '2xl': ['calc(1.5rem * var(--_fs-mult, 1))',   { lineHeight: 'calc(2rem * var(--_fs-mult, 1))' }],
        '3xl': ['calc(1.875rem * var(--_fs-mult, 1))', { lineHeight: 'calc(2.25rem * var(--_fs-mult, 1))' }],
        '4xl': ['calc(2.25rem * var(--_fs-mult, 1))',  { lineHeight: 'calc(2.5rem * var(--_fs-mult, 1))' }],
        '5xl': ['calc(3rem * var(--_fs-mult, 1))',     { lineHeight: '1' }],
        '6xl': ['calc(3.75rem * var(--_fs-mult, 1))',  { lineHeight: '1' }],
        '7xl': ['calc(4.5rem * var(--_fs-mult, 1))',   { lineHeight: '1' }],
        '8xl': ['calc(6rem * var(--_fs-mult, 1))',     { lineHeight: '1' }],
        '9xl': ['calc(8rem * var(--_fs-mult, 1))',     { lineHeight: '1' }],
      },
      fontFamily: {
        body: ['var(--font-body)', 'cursive'],
        headline: ['var(--font-headline)', 'cursive'],
        label: ['var(--font-body)', 'cursive'],
        accent: ['var(--font-accent)', 'sans-serif'],
        mono: ['var(--font-mono)', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      keyframes: {
        'target-shimmer': {
          '0%, 100%': { opacity: '0.55', filter: 'blur(1px)', transform: 'scale(1)' },
          '50%': { opacity: '0.85', filter: 'blur(0.5px)', transform: 'scale(1.02)' },
        },
        'intuition-pulse': {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(251,191,36,0)', transform: 'scale(1)' },
          '50%': { boxShadow: '0 0 8px 2px rgba(251,191,36,0.15)', transform: 'scale(1.04)' },
        },
        'intuition-flash': {
          '0%': { opacity: '0', transform: 'scale(0.7)' },
          '20%': { opacity: '1', transform: 'scale(1.1)' },
          '40%': { opacity: '1', transform: 'scale(1)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
      },
      animation: {
        'target-shimmer': 'target-shimmer 3.5s ease-in-out infinite',
        'intuition-pulse': 'intuition-pulse 2.5s ease-in-out infinite',
        'intuition-flash': 'intuition-flash 150ms ease-out forwards',
      },
    },
  },
  plugins: [],
};
