// Field schemas for the admin EntityForm. One config per entity type.
// Field shape — see FieldRenderer.jsx for renderer contract.

export const campaignFields = [
  { key: 'name', type: 'text', label: 'Nazwa' },
  { key: 'genre', type: 'text', label: 'Gatunek' },
  { key: 'tone', type: 'text', label: 'Ton' },
  { key: 'isPublic', type: 'bool', label: 'Publiczna' },
  { key: 'currentLocationName', type: 'text', label: 'Aktualna lokacja (nazwa)' },
  {
    key: 'currentLocation',
    type: 'polymorphRef',
    label: 'Aktualna lokacja (ref)',
    kindKey: 'currentLocationKind',
    idKey: 'currentLocationId',
    targets: { world: 'WorldLocation', campaign: 'CampaignLocation' },
  },
  { key: 'currentX', type: 'number', label: 'X (km)' },
  { key: 'currentY', type: 'number', label: 'Y (km)' },
  { key: 'livingWorldEnabled', type: 'bool', label: 'Living World' },
  { key: 'questGraphEnabled', type: 'bool', label: 'Quest graph' },
  { key: 'difficultyTier', type: 'enum', options: ['low', 'medium', 'high', 'deadly'], label: 'Trudność' },
  { key: 'worldTimeRatio', type: 'number', label: 'Time ratio' },
  { key: 'pendingSlip', type: 'textarea', label: 'pendingSlip', rows: 2 },
  { key: 'pendingProvidence', type: 'json', label: 'pendingProvidence' },
  { key: 'coreState', type: 'json', label: 'coreState (JSONB)', rows: 16 },
];

export const questFields = [
  { key: 'name', type: 'text', label: 'Nazwa', required: true },
  { key: 'questId', type: 'text', label: 'questId (slug)' },
  { key: 'type', type: 'enum', options: ['main', 'side', 'rumor', 'personal'], label: 'Typ' },
  { key: 'status', type: 'enum', options: ['active', 'completed', 'stalled', 'failed'], label: 'Status' },
  { key: 'description', type: 'textarea', label: 'Opis', rows: 3 },
  { key: 'questGiverId', type: 'relRef', target: 'CampaignNPC.npcId', label: 'Quest giver (npcId)' },
  { key: 'turnInNpcId', type: 'relRef', target: 'CampaignNPC.npcId', label: 'Turn-in NPC (npcId)' },
  {
    key: 'location',
    type: 'polymorphRef',
    label: 'Lokacja questu',
    kindKey: 'locationKind',
    idKey: 'locationId',
    targets: { world: 'WorldLocation', campaign: 'CampaignLocation' },
  },
  { key: 'completionCondition', type: 'textarea', label: 'completionCondition', rows: 2 },
  { key: 'forcedGiver', type: 'bool', label: 'forcedGiver' },
  { key: 'reward', type: 'json', label: 'Reward (JSON)' },
  { key: 'mutationLog', type: 'json', label: 'mutationLog (read-only)', readonly: true },
];

export const objectiveFields = [
  { key: 'description', type: 'textarea', label: 'Opis', required: true, rows: 2 },
  { key: 'displayOrder', type: 'number', label: 'displayOrder' },
  { key: 'progress', type: 'number', label: 'Progress' },
  { key: 'targetAmount', type: 'number', label: 'Target amount' },
  {
    key: 'status',
    type: 'enum',
    options: ['pending', 'done', 'locked', 'skipped', 'failed'],
    label: 'Status',
  },
  { key: 'nodeKey', type: 'text', label: 'nodeKey (slug)' },
  { key: 'metadata', type: 'json', label: 'metadata (parents/unlocks/branchType/failsOn)' },
];

export const npcFields = [
  { key: 'name', type: 'text', label: 'Imię', required: true },
  { key: 'gender', type: 'enum', options: ['male', 'female', 'other', 'unknown'], label: 'Płeć' },
  { key: 'role', type: 'text', label: 'Rola' },
  { key: 'attitude', type: 'enum', options: ['hostile', 'unfriendly', 'neutral', 'friendly', 'devoted'], label: 'Postawa' },
  { key: 'disposition', type: 'number', label: 'Disposition (-100..100)' },
  { key: 'alive', type: 'bool', label: 'Żyje' },
  { key: 'category', type: 'enum', options: ['commoner', 'merchant', 'guard', 'mage', 'noble', 'monster'], label: 'Kategoria' },
  { key: 'isAgent', type: 'bool', label: 'isAgent' },
  { key: 'level', type: 'number', label: 'Poziom' },
  { key: 'race', type: 'text', label: 'Rasa' },
  { key: 'creatureKind', type: 'text', label: 'creatureKind' },
  { key: 'factionId', type: 'text', label: 'factionId' },
  { key: 'lastLocation', type: 'text', label: 'lastLocation (legacy name)' },
  {
    key: 'lastLoc',
    type: 'polymorphRef',
    label: 'lastLocation ref',
    kindKey: 'lastLocationKind',
    idKey: 'lastLocationId',
    targets: { world: 'WorldLocation', campaign: 'CampaignLocation' },
  },
  { key: 'worldNpcId', type: 'relRef', target: 'WorldNPC.id', label: 'WorldNPC link' },
  { key: 'personality', type: 'textarea', label: 'Osobowość', rows: 3 },
  { key: 'appearance', type: 'textarea', label: 'Wygląd', rows: 2 },
  { key: 'dialect', type: 'textarea', label: 'Sposób mówienia', rows: 2 },
  { key: 'notes', type: 'textarea', label: 'Notatki', rows: 3 },
  { key: 'activeGoal', type: 'text', label: 'activeGoal' },
  { key: 'goalProgress', type: 'json', label: 'goalProgress' },
  { key: 'stats', type: 'json', label: 'stats (statblock)' },
  { key: 'portraitUrl', type: 'text', label: 'portraitUrl' },
  { key: 'spriteUrl', type: 'text', label: 'spriteUrl' },
];

export const worldNpcFields = [
  { key: 'name', type: 'text', label: 'Imię', required: true },
  { key: 'role', type: 'text', label: 'Rola' },
  { key: 'alignment', type: 'text', label: 'Alignment' },
  { key: 'alive', type: 'bool', label: 'Żyje' },
  { key: 'category', type: 'enum', options: ['commoner', 'merchant', 'guard', 'mage', 'noble', 'monster'], label: 'Kategoria' },
  { key: 'keyNpc', type: 'bool', label: 'keyNpc' },
  { key: 'level', type: 'number', label: 'Poziom' },
  { key: 'race', type: 'text', label: 'Rasa' },
  { key: 'creatureKind', type: 'text', label: 'creatureKind' },
  { key: 'currentLocationId', type: 'relRef', target: 'WorldLocation.id', label: 'currentLocationId' },
  { key: 'homeLocationId', type: 'relRef', target: 'WorldLocation.id', label: 'homeLocationId' },
  { key: 'personality', type: 'textarea', label: 'Osobowość', rows: 3 },
  { key: 'appearance', type: 'textarea', label: 'Wygląd', rows: 2 },
  { key: 'dialect', type: 'textarea', label: 'Sposób mówienia', rows: 2 },
  { key: 'activeGoal', type: 'text', label: 'activeGoal' },
  { key: 'goalProgress', type: 'json', label: 'goalProgress' },
  { key: 'schedule', type: 'json', label: 'schedule' },
  { key: 'stats', type: 'json', label: 'stats' },
  { key: 'spriteUrl', type: 'text', label: 'spriteUrl' },
];

export const worldLocationFields = [
  { key: 'canonicalName', type: 'text', label: 'canonicalName', required: true },
  { key: 'displayName', type: 'text', label: 'displayName' },
  { key: 'description', type: 'textarea', label: 'Opis', rows: 4 },
  { key: 'category', type: 'text', label: 'Kategoria' },
  { key: 'region', type: 'text', label: 'Region' },
  {
    key: 'locationType',
    type: 'enum',
    options: ['generic', 'city', 'town', 'village', 'hamlet', 'inn', 'fortress', 'ruin', 'dungeon', 'wilderness', 'special'],
    label: 'Typ',
  },
  { key: 'dangerLevel', type: 'enum', options: ['safe', 'low', 'moderate', 'high', 'deadly'], label: 'Zagrożenie' },
  { key: 'parentLocationId', type: 'relRef', target: 'WorldLocation.id', label: 'parentLocationId' },
  { key: 'regionX', type: 'number', label: 'regionX' },
  { key: 'regionY', type: 'number', label: 'regionY' },
  { key: 'biome', type: 'text', label: 'biome' },
  { key: 'anchorType', type: 'text', label: 'anchorType' },
  { key: 'knownByDefault', type: 'bool', label: 'knownByDefault' },
  { key: 'aliases', type: 'json', label: 'aliases' },
  { key: 'tags', type: 'json', label: 'tags' },
  { key: 'tacticalGrid', type: 'json', label: 'tacticalGrid' },
  { key: 'dungeonState', type: 'json', label: 'dungeonState' },
];

export const campaignLocationFields = [
  { key: 'name', type: 'text', label: 'Nazwa', required: true },
  { key: 'canonicalSlug', type: 'text', label: 'canonicalSlug', required: true },
  { key: 'description', type: 'textarea', label: 'Opis', rows: 4 },
  { key: 'category', type: 'text', label: 'Kategoria' },
  {
    key: 'locationType',
    type: 'enum',
    options: ['generic', 'city', 'town', 'village', 'hamlet', 'inn', 'fortress', 'ruin', 'dungeon', 'wilderness', 'special'],
    label: 'Typ',
  },
  { key: 'dangerLevel', type: 'enum', options: ['safe', 'low', 'moderate', 'high', 'deadly'], label: 'Zagrożenie' },
  { key: 'region', type: 'text', label: 'Region' },
  { key: 'regionX', type: 'number', label: 'regionX' },
  { key: 'regionY', type: 'number', label: 'regionY' },
  {
    key: 'parent',
    type: 'polymorphRef',
    label: 'parentLocation',
    kindKey: 'parentLocationKind',
    idKey: 'parentLocationId',
    targets: { world: 'WorldLocation', campaign: 'CampaignLocation' },
  },
  { key: 'biome', type: 'text', label: 'biome' },
  { key: 'anchorType', type: 'text', label: 'anchorType' },
  { key: 'aliases', type: 'json', label: 'aliases' },
  { key: 'tags', type: 'json', label: 'tags' },
];

export const locationEdgeFields = [
  {
    key: 'from',
    type: 'polymorphRef',
    label: 'From',
    kindKey: 'fromKind',
    idKey: 'fromId',
    targets: { world: 'WorldLocation', campaign: 'CampaignLocation' },
  },
  {
    key: 'to',
    type: 'polymorphRef',
    label: 'To',
    kindKey: 'toKind',
    idKey: 'toId',
    targets: { world: 'WorldLocation', campaign: 'CampaignLocation' },
  },
  {
    key: 'edgeType',
    type: 'enum',
    options: ['road', 'path', 'door', 'stairs', 'portal', 'secret_path', 'visible_from', 'audible_from', 'controlled_by'],
    label: 'Typ krawędzi',
  },
  {
    key: 'category',
    type: 'enum',
    options: ['movement', 'perception', 'social', 'narrative', 'temporal'],
    label: 'Kategoria',
  },
  { key: 'bidirectional', type: 'bool', label: 'bidirectional' },
  { key: 'weight', type: 'number', label: 'weight' },
  { key: 'confidence', type: 'number', label: 'confidence (0-1)' },
  {
    key: 'discoveryState',
    type: 'enum',
    options: ['unknown', 'rumored', 'discovered', 'verified'],
    label: 'discoveryState',
  },
  { key: 'isActive', type: 'bool', label: 'isActive' },
  { key: 'metadata', type: 'json', label: 'metadata' },
];

export const sceneFields = [
  { key: 'narrative', type: 'textarea', label: 'Narracja', rows: 8 },
  { key: 'chosenAction', type: 'text', label: 'chosenAction' },
  { key: 'imagePrompt', type: 'textarea', label: 'imagePrompt', rows: 2 },
  { key: 'imageUrl', type: 'text', label: 'imageUrl' },
  { key: 'soundEffect', type: 'text', label: 'soundEffect' },
  { key: 'suggestedActions', type: 'json', label: 'suggestedActions' },
  { key: 'dialogueSegments', type: 'json', label: 'dialogueSegments' },
  { key: 'diceRoll', type: 'json', label: 'diceRoll' },
  { key: 'stateChanges', type: 'json', label: 'stateChanges' },
  { key: 'scenePacing', type: 'text', label: 'scenePacing' },
];
