export const AI_TASK_CATEGORIES = [
  {
    key: 'sceneGeneration',
    label: 'Scene generation',
    defaultTier: 'premium',
    group: 'Scenes',
    description: 'Full solo scene stream.',
  },
  {
    key: 'sceneShortcutNarrative',
    label: 'Shortcut narrative',
    defaultTier: 'standard',
    group: 'Scenes',
    description: 'Short combat/trade fast-path narration.',
  },
  {
    key: 'campaignGeneration',
    label: 'Campaign generation',
    defaultTier: 'premium',
    group: 'Campaigns',
    description: 'Campaign bootstrap stream.',
  },
  {
    key: 'intentClassification',
    label: 'Intent classification',
    defaultTier: 'nano',
    group: 'Classifiers',
    description: 'Pre-scene context selector.',
  },
  {
    key: 'memoryExtraction',
    label: 'Memory extraction',
    defaultTier: 'nanoReasoning',
    group: 'Memory',
    description: 'Scene summaries, needs, journal and location memory.',
  },
  {
    key: 'sceneMemoryCompression',
    label: 'Scene memory compression',
    defaultTier: 'nanoReasoning',
    group: 'Memory',
    description: 'Compress a completed scene into persistent facts.',
  },
  {
    key: 'locationSummary',
    label: 'Location summary',
    defaultTier: 'nanoReasoning',
    group: 'Memory',
    description: 'Update per-location narrative summary.',
  },
  {
    key: 'imagePrompt',
    label: 'Image prompt',
    defaultTier: 'nano',
    group: 'Images',
    description: 'Generate compact image prompts.',
  },
  {
    key: 'imagePromptEnhancement',
    label: 'Image prompt enhancement',
    defaultTier: 'standard',
    group: 'Images',
    description: 'Enhance user image prompts.',
  },
  {
    key: 'imageTranslation',
    label: 'Image prompt translation',
    defaultTier: 'nano',
    group: 'Images',
    description: 'Translate image prompt seeds to English.',
  },
  {
    key: 'npcPortraitPrompt',
    label: 'NPC portrait prompt',
    defaultTier: 'nano',
    group: 'Images',
    description: 'Build NPC portrait prompts.',
  },
  {
    key: 'storyPrompt',
    label: 'Story prompt',
    defaultTier: 'standard',
    group: 'Creator',
    description: 'Campaign premise suggestions.',
  },
  {
    key: 'characterLegend',
    label: 'Character legend',
    defaultTier: 'standard',
    group: 'Creator',
    description: 'Character legend snippets.',
  },
  {
    key: 'quickBeat',
    label: 'Quick beat',
    defaultTier: 'nano',
    group: 'Scenes',
    description: 'Lightweight mini-action response.',
  },
  {
    key: 'creatureEncounter',
    label: 'Creature encounter',
    defaultTier: 'nano',
    group: 'Scenes',
    description: 'Encounter prompt helper.',
  },
  {
    key: 'yassatoCameo',
    label: 'Yassato cameo',
    defaultTier: 'nano',
    group: 'Scenes',
    description: 'Special cameo scene helper.',
  },
  {
    key: 'combatResolution',
    label: 'Combat resolution',
    defaultTier: 'standard',
    group: 'Combat',
    description: 'Resolve a combat turn.',
  },
  {
    key: 'combatCommentary',
    label: 'Combat commentary',
    defaultTier: 'standard',
    group: 'Combat',
    description: 'Mid-combat narration.',
  },
  {
    key: 'questVerification',
    label: 'Quest verification',
    defaultTier: 'standard',
    group: 'Quests',
    description: 'Verify objective completion.',
  },
  {
    key: 'questProgressCheck',
    label: 'Quest progress check',
    defaultTier: 'nano',
    group: 'Quests',
    description: 'Match scenes against active quest objectives.',
  },
  {
    key: 'questWrapup',
    label: 'Quest wrap-up',
    defaultTier: 'nano',
    group: 'Quests',
    description: 'Fallback quest wrap-up line.',
  },
  {
    key: 'recapGeneration',
    label: 'Recap generation',
    defaultTier: 'standard',
    group: 'Memory',
    description: 'Campaign recap and merge.',
  },
  {
    key: 'npcDialog',
    label: 'NPC dialog',
    defaultTier: 'standard',
    group: 'Living World',
    description: 'Direct NPC conversation.',
  },
  {
    key: 'npcAppearance',
    label: 'NPC appearance',
    defaultTier: 'standard',
    group: 'Living World',
    description: 'Fill NPC appearance and dialect.',
  },
  {
    key: 'npcOfflineSummary',
    label: 'NPC offline summary',
    defaultTier: 'nanoReasoning',
    group: 'Living World',
    description: 'Summarize companion off-screen activity.',
  },
  {
    key: 'dmMemoryUpdate',
    label: 'DM memory update',
    defaultTier: 'nanoReasoning',
    group: 'Memory',
    description: 'Update persistent DM memory entries.',
  },
  {
    key: 'spellClassification',
    label: 'Spell classification',
    defaultTier: 'nano',
    group: 'Magic',
    description: 'Classify spell schools.',
  },
  {
    key: 'spellInvention',
    label: 'Spell invention',
    defaultTier: 'premium',
    group: 'Magic',
    description: 'Analyze invented spells.',
  },
  {
    key: 'selfQuest',
    label: 'Self quest',
    defaultTier: 'nano',
    group: 'Quests',
    description: 'Validate custom player quest.',
  },
  {
    key: 'incidentAnalysis',
    label: 'Incident analysis',
    defaultTier: 'premium',
    group: 'Diagnostics',
    description: 'Analyze player incident reports.',
  },
  {
    key: 'graphExtraction',
    label: 'Graph extraction',
    defaultTier: 'nano',
    group: 'Location Graph',
    description: 'Extract location graph updates.',
  },
  {
    key: 'graphRevision',
    label: 'Graph revision',
    defaultTier: 'standard',
    group: 'Location Graph',
    description: 'AI review and correction of location graph.',
  },
  {
    key: 'travelCheck',
    label: 'Travel check',
    defaultTier: 'nano',
    group: 'Travel',
    description: 'Long-distance travel feasibility.',
  },
  {
    key: 'multiplayerScene',
    label: 'Multiplayer scene',
    defaultTier: 'premium',
    group: 'Multiplayer',
    description: 'Multiplayer AI scene/campaign calls.',
  },
  {
    key: 'characterBadge',
    label: 'Character badge',
    defaultTier: 'nano',
    group: 'Characters',
    description: 'Character summary badge.',
  },
  {
    key: 'badgeEvaluation',
    label: 'Badge evaluation',
    defaultTier: 'nano',
    group: 'Characters',
    description: 'Periodic medal evaluation from recent scenes.',
  },
  {
    key: 'badgeImagePrompt',
    label: 'Badge image prompt',
    defaultTier: 'nano',
    group: 'Images',
    description: 'Build image prompt for a medal/badge icon.',
  },
  {
    key: 'postCampaignWorld',
    label: 'Post-campaign world',
    defaultTier: 'standard',
    group: 'Living World',
    description: 'Writeback facts and promotion verdicts.',
  },
  {
    key: 'questAudit',
    label: 'Quest audit',
    defaultTier: 'nano',
    group: 'Quests',
    description: 'Check whether a side quest is major.',
  },
  {
    key: 'npcAgentTick',
    label: 'NPC agent tick',
    defaultTier: 'nano',
    group: 'Living World',
    description: 'Admin-triggered NPC background action.',
  },
  {
    key: 'killJudge',
    label: 'Kill judge',
    defaultTier: 'nano',
    group: 'Living World',
    description: 'Judge whether NPC harm was justified.',
  },
  {
    key: 'chargenAppearance',
    label: 'Chargen appearance',
    defaultTier: 'nano',
    group: 'Images',
    description: 'Pick LPC chargen appearance for a character or NPC.',
  },
  {
    key: 'auxiliary',
    label: 'Legacy auxiliary',
    defaultTier: 'standard',
    group: 'Legacy',
    description: 'Kept only for old saved overrides.',
    legacy: true,
  },
];

export const AI_TASK_CATEGORY_KEYS = AI_TASK_CATEGORIES.map((category) => category.key);

export const AI_TASK_CATEGORY_BY_KEY = Object.fromEntries(
  AI_TASK_CATEGORIES.map((category) => [category.key, category]),
);

export function getAiTaskDefaultTier(taskCategory) {
  return AI_TASK_CATEGORY_BY_KEY[taskCategory]?.defaultTier || 'premium';
}
