/**
 * Stable keys for inventory items and materials.
 * Used as composite-PK component on Postgres tables (F4) so the same
 * helper has to live in both FE and BE.
 *
 * Items/materials stack by lowercased + ASCII-slugged name. Two items
 * with the same name merge into one stack regardless of `props` —
 * intentional simplification (F4 decision: option A).
 */

// Polish letters that don't decompose via NFKD (most do; Ł/ł and a few others
// don't because they're standalone codepoints, not base+combining).
const STANDALONE_REPLACEMENTS = { 'ł': 'l', 'Ł': 'l' };

export function slugifyItemName(value) {
  let s = String(value || '');
  for (const [from, to] of Object.entries(STANDALONE_REPLACEMENTS)) {
    s = s.split(from).join(to);
  }
  const slug = s
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .trim()
    .replace(/\s+/g, '_')
    .replace(/[^a-z0-9_]/g, '')
    .replace(/^_+|_+$/g, '');
  return slug || 'unnamed';
}

// ── Power scoring for combine / enchant validation ──
//
// "Result must be at least as strong as the sum of its sources" — encoded as
// a single composite number so combine and enchant can compare results to
// sources without a full combat-sim.
//
//   score = rarityTier * 10 + min(maxFlatDamage, 99)
//
// rarityTier dominates: a legendary common-flat item beats a common epic-flat.
// maxFlatDamage gives intra-tier ordering for weapons/spells that share a
// rarity.

const RARITY_TIER = {
  common: 1,
  uncommon: 2,
  rare: 3,
  epic: 4,
  legendary: 5,
};

export const RARITY_ORDER = ['common', 'uncommon', 'rare', 'epic', 'legendary'];

const MAX_RARITY_TIER = RARITY_ORDER.length;
export const MAX_POWER_SCORE = MAX_RARITY_TIER * 10 + 99;

function normalizeRarity(value) {
  const s = String(value || '').toLowerCase().trim();
  if (RARITY_TIER[s]) return s;
  return 'common';
}

/**
 * Scan `attackModes.{melee,ranged,aoe}.damageComponents[].flat` and take the
 * maximum. Weapons that scale from str/dex have no flat — that's fine, they
 * fall back to the rarityTier signal alone (which is still ordered).
 */
function computeMaxAttackFlat(attackModes) {
  if (!attackModes || typeof attackModes !== 'object') return 0;
  let max = 0;
  for (const key of ['melee', 'ranged', 'aoe']) {
    const mode = attackModes[key];
    if (!mode || !Array.isArray(mode.damageComponents)) continue;
    for (const comp of mode.damageComponents) {
      if (!comp || typeof comp !== 'object') continue;
      const flat = Number(comp.flat);
      if (Number.isFinite(flat) && flat > max) max = flat;
      // fixedDamage means "always exactly this much" — count it as flat for
      // the purpose of comparing item power.
      const fixed = Number(comp.fixedDamage);
      if (Number.isFinite(fixed) && fixed > max) max = fixed;
    }
  }
  return max;
}

/**
 * Composite power score for an inventory item (FE-snapshot shape).
 *
 * Looks at both top-level `attackModes` and `props.attackModes` — items
 * generated by AI land in `props.attackModes`, BE-resolved equipment exposes
 * it at the top level after `gameData.resolveBaseType`.
 */
export function itemPowerScore(item) {
  if (!item) return 0;
  const tier = RARITY_TIER[normalizeRarity(item.rarity)] ?? 1;
  const attackModes = item.attackModes ?? item.props?.attackModes ?? null;
  const maxFlat = Math.min(computeMaxAttackFlat(attackModes), 99);
  return Math.min(MAX_POWER_SCORE, tier * 10 + maxFlat);
}

/**
 * Bump rarity up one tier; caps at `legendary`.
 */
export function bumpRarity(current) {
  const idx = RARITY_ORDER.indexOf(normalizeRarity(current));
  if (idx < 0) return 'uncommon';
  return RARITY_ORDER[Math.min(idx + 1, RARITY_ORDER.length - 1)];
}

export function normalizeItemRarity(value) {
  return normalizeRarity(value);
}
